// Code generated by goctl. DO NOT EDIT.
// Source: interaction.proto

package server

import (
	"context"

	"zero-tiktok/service/interaction/internal/logic"
	"zero-tiktok/service/interaction/internal/svc"
	"zero-tiktok/service/interaction/pb/zero-tiktok/service/interaction"
)

type InteractionServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedInteractionServiceServer
}

func NewInteractionServiceServer(svcCtx *svc.ServiceContext) *InteractionServiceServer {
	return &InteractionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServiceServer) Comment(ctx context.Context, in *interaction.CommentRequest) (*interaction.CommentResponse, error) {
	l := logic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}

func (s *InteractionServiceServer) CommentList(ctx context.Context, in *interaction.CommentListRequest) (*interaction.CommentListResponse, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}

func (s *InteractionServiceServer) Relation(ctx context.Context, in *interaction.RelationRequest) (*interaction.RelationResponse, error) {
	l := logic.NewRelationLogic(ctx, s.svcCtx)
	return l.Relation(in)
}

func (s *InteractionServiceServer) FollowList(ctx context.Context, in *interaction.FollowListRequest) (*interaction.FollowListResponse, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *InteractionServiceServer) FollowerList(ctx context.Context, in *interaction.FollowerListRequest) (*interaction.FollowerListResponse, error) {
	l := logic.NewFollowerListLogic(ctx, s.svcCtx)
	return l.FollowerList(in)
}

func (s *InteractionServiceServer) FriendList(ctx context.Context, in *interaction.FriendListRequest) (*interaction.FriendListResponse, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}

func (s *InteractionServiceServer) HasFollowed(ctx context.Context, in *interaction.HasFollowedRequest) (*interaction.HasFollowedResponse, error) {
	l := logic.NewHasFollowedLogic(ctx, s.svcCtx)
	return l.HasFollowed(in)
}
