// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"zero-tiktok/service/video/internal/logic"
	"zero-tiktok/service/video/internal/svc"
	"zero-tiktok/service/video/pb/zero-tiktok/service/video"
)

type VideoServiceServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServiceServer
}

func NewVideoServiceServer(svcCtx *svc.ServiceContext) *VideoServiceServer {
	return &VideoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServiceServer) Feed(ctx context.Context, in *video.FeedRequest) (*video.VideoListResp, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}

func (s *VideoServiceServer) Publish(ctx context.Context, in *video.PublishRequest) (*video.VideoListResp, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *VideoServiceServer) Favorite(ctx context.Context, in *video.FavoriteAction) (*video.FavoriteActionResp, error) {
	l := logic.NewFavoriteLogic(ctx, s.svcCtx)
	return l.Favorite(in)
}

func (s *VideoServiceServer) FavoriteList(ctx context.Context, in *video.FavoriteRequest) (*video.VideoListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *VideoServiceServer) IsFavorite(ctx context.Context, in *video.IsFavoriteReq) (*video.IsFavoriteResp, error) {
	l := logic.NewIsFavoriteLogic(ctx, s.svcCtx)
	return l.IsFavorite(in)
}
