// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserLoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserTokenResp struct {
	Code   int64  `json:"code"`
	Msg    string `json:"msg"`
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
}
